# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2022, macos-12]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Gradle
      # You may pin to the exact commit or the version.
      uses: gradle/gradle-build-action@3fbe033aaae657f011f88f29be9e65ed26bd29ef



      with:
        arguments: build jacocoTestReport
        build-root-directory: ENG1
    - name: Generate jar file
      run: gradlew desktop:dist

    - name: Upload JaCoCo coverage report as a workflow artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        name: jacoco-report-${{ matrix.os }}
        path: ENG1/core/build/reports/test/html
    - name: Upload library JAR
      uses: actions/upload-artifact@v3.1.1
      with:
        name: lib-${{matrix.os}}.jar
        path: ENG1/desktop/build/libs/desktop-1.0.jar